% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Assignment 6: GLMs (Linear Regressios, ANOVA, \& t-tests)},
  pdfauthor={Emma Childs},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Assignment 6: GLMs (Linear Regressios, ANOVA, \& t-tests)}
\author{Emma Childs}
\date{Spring 2023}

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Environmental Data Analytics on
generalized linear models.

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Rename this file
  \texttt{\textless{}FirstLast\textgreater{}\_A06\_GLMs.Rmd} (replacing
  \texttt{\textless{}FirstLast\textgreater{}} with your first and last
  name).
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\end{enumerate}

\hypertarget{set-up-your-session}{%
\subsection{Set up your session}\label{set-up-your-session}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Set up your session. Check your working directory. Load the tidyverse,
  agricolae and other needed packages. Import the \emph{raw} NTL-LTER
  raw data file for chemistry/physics
  (\texttt{NTL-LTER\_Lake\_ChemistryPhysics\_Raw.csv}). Set date columns
  to date objects.
\item
  Build a ggplot theme and set it as your default theme.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#1}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.0     v readr     2.1.4
## v forcats   1.0.0     v stringr   1.5.0
## v ggplot2   3.4.1     v tibble    3.1.8
## v lubridate 1.9.2     v tidyr     1.3.0
## v purrr     1.0.1     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(agricolae)   }
\FunctionTok{library}\NormalTok{(here)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## here() starts at /home/guest/EDA-Spring2023
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{here}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/home/guest/EDA-Spring2023"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{NTL\_Lake\_ChemPhys }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"Data/Raw/NTL{-}LTER\_Lake\_ChemistryPhysics\_Raw.csv"}\NormalTok{), }\AttributeTok{stringsAsFactors =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{NTL\_Lake\_ChemPhys}\SpecialCharTok{$}\NormalTok{sampledate }\OtherTok{\textless{}{-}} \FunctionTok{mdy}\NormalTok{(NTL\_Lake\_ChemPhys}\SpecialCharTok{$}\NormalTok{sampledate)}
\CommentTok{\#installed packages and imported dataset}

\CommentTok{\#2}
\NormalTok{mytheme }\OtherTok{\textless{}{-}} \FunctionTok{theme\_classic}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{12}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{), }
        \AttributeTok{legend.position =} \StringTok{"top"}\NormalTok{)}
\FunctionTok{theme\_set}\NormalTok{(mytheme)}
\CommentTok{\#set a theme}
\end{Highlighting}
\end{Shaded}

\hypertarget{simple-regression}{%
\subsection{Simple regression}\label{simple-regression}}

Our first research question is: Does mean lake temperature recorded
during July change with depth across all lakes?

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  State the null and alternative hypotheses for this question:
  \textgreater{} Answer: H0: The mean lake temperature recorded during
  July does not change with depth across all lakes. Ha: The mean lake
  temperature recorded during July does change with depth across all
  lakes.
\item
  Wrangle your NTL-LTER dataset with a pipe function so that the records
  meet the following criteria:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Only dates in July.
\item
  Only the columns: \texttt{lakename}, \texttt{year4}, \texttt{daynum},
  \texttt{depth}, \texttt{temperature\_C}
\item
  Only complete cases (i.e., remove NAs)
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Visualize the relationship among the two continuous variables with a
  scatter plot of temperature by depth. Add a smoothed line showing the
  linear model, and limit temperature values from 0 to 35 °C. Make this
  plot look pretty and easy to read.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#4}
\NormalTok{NTL\_Lake\_ChemPhys\_subset }\OtherTok{\textless{}{-}}
\NormalTok{  NTL\_Lake\_ChemPhys }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\FunctionTok{month}\NormalTok{(sampledate) }\SpecialCharTok{==} \DecValTok{7}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(lakename}\SpecialCharTok{:}\NormalTok{daynum, depth, temperature\_C) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{()}
\CommentTok{\#Wrangled a pipe function so that we filtered for July, and only depicted the columns: lakename, year4, daynum, depth, temperature\_C}

\CommentTok{\#5}
\NormalTok{NTL\_Lake\_ChemPhys\_plot }\OtherTok{\textless{}{-}}
\FunctionTok{ggplot}\NormalTok{(NTL\_Lake\_ChemPhys\_subset, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{depth,}\AttributeTok{y=}\NormalTok{temperature\_C)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color=}\StringTok{\textquotesingle{}darkblue\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{35}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\StringTok{"lm"}\NormalTok{, }\AttributeTok{color=}\StringTok{"red"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Depth (m)"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Temperature (°C)"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Lake Temperature by Depth"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(NTL\_Lake\_ChemPhys\_plot) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 24 rows containing missing values (`geom_smooth()`).
\end{verbatim}

\includegraphics{EmmaChilds_A06_GLMs_files/figure-latex/scatterplot-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#plotted temperature by depth for this subset of data with a smoothed line for the linear model}

\CommentTok{\#?drop\_na {-} trying to understand this function better because missing rows were reported {-} no conclusion }
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Interpret the figure. What does it suggest with regards to the
  response of temperature to depth? Do the distribution of points
  suggest about anything about the linearity of this trend?
\end{enumerate}

\begin{quote}
Answer: As depth increases, temperature of the lake decreases. However,
past a certain depth (starting somewhere around 7-9m - meters?), the
relationship seems to become less linear based on the distribution of
points.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Perform a linear regression to test the relationship and display the
  results
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#7}
\NormalTok{NTL\_Lake\_regression }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\AttributeTok{data =}\NormalTok{ NTL\_Lake\_ChemPhys\_subset, temperature\_C }\SpecialCharTok{\textasciitilde{}}\NormalTok{ depth)}
\FunctionTok{summary}\NormalTok{(NTL\_Lake\_regression)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ depth, data = NTL_Lake_ChemPhys_subset)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.5173 -3.0192  0.0633  2.9365 13.5834 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 21.95597    0.06792   323.3   <2e-16 ***
## depth       -1.94621    0.01174  -165.8   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.835 on 9726 degrees of freedom
## Multiple R-squared:  0.7387, Adjusted R-squared:  0.7387 
## F-statistic: 2.75e+04 on 1 and 9726 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Interpret your model results in words. Include how much of the
  variability in temperature is explained by changes in depth, the
  degrees of freedom on which this finding is based, and the statistical
  significance of the result. Also mention how much temperature is
  predicted to change for every 1m change in depth.
\end{enumerate}

\begin{quote}
Answer: The r\^{}2 value of 0.7387 tells us that there is 73.87\%
variability in y (temp) that is ``explained'' by the independent
variable, x (depth). This finding is based on 9726 degrees of freedom.
Our p-value is less than 0.05, so the depth is significant enough to be
included as a factor impacting temperature. In fact, the temperature is
predicted to decrease by -1.94621 degrees Celsius for every 1m change in
depth.
\end{quote}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{multiple-regression}{%
\subsection{Multiple regression}\label{multiple-regression}}

Let's tackle a similar question from a different approach. Here, we want
to explore what might the best set of predictors for lake temperature in
July across the monitoring period at the North Temperate Lakes LTER.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\item
  Run an AIC to determine what set of explanatory variables (year4,
  daynum, depth) is best suited to predict temperature.
\item
  Run a multiple regression on the recommended set of variables.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#9}
\NormalTok{NTL.metagaming }\OtherTok{\textless{}{-}}\NormalTok{ NTL\_Lake\_ChemPhys\_subset }
\NormalTok{noise }\OtherTok{\textless{}{-}} \FunctionTok{runif}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(NTL\_Lake\_ChemPhys\_subset))}
\NormalTok{NTL.metagaming}\SpecialCharTok{$}\NormalTok{noise }\OtherTok{\textless{}{-}}\NormalTok{ noise}
\CommentTok{\#This first section was an experiment...I was working with a friend who does a lot of coding regularly, and they had me create a "metagaming" scenario with a column of fake noise numbers to see if the AIC would kick it out as being not significant. This was helpful for me, but my real code for the regression and step function is below.}

\NormalTok{NTLbyALL.regression }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\AttributeTok{data=}\NormalTok{NTL.metagaming, temperature\_C }\SpecialCharTok{\textasciitilde{}}\NormalTok{ depth }\SpecialCharTok{+}\NormalTok{ year4 }\SpecialCharTok{+}\NormalTok{ daynum }\SpecialCharTok{+}\NormalTok{ depth }\SpecialCharTok{+}\NormalTok{ noise)}
\FunctionTok{step}\NormalTok{(NTLbyALL.regression)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=26067.46
## temperature_C ~ depth + year4 + daynum + depth + noise
## 
##          Df Sum of Sq    RSS   AIC
## - noise   1         1 141687 26066
## <none>                141686 26067
## - year4   1       102 141787 26072
## - daynum  1      1237 142923 26150
## - depth   1    404475 546160 39191
## 
## Step:  AIC=26065.53
## temperature_C ~ depth + year4 + daynum
## 
##          Df Sum of Sq    RSS   AIC
## <none>                141687 26066
## - year4   1       101 141788 26070
## - daynum  1      1237 142924 26148
## - depth   1    404475 546161 39189
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ depth + year4 + daynum, data = NTL.metagaming)
## 
## Coefficients:
## (Intercept)        depth        year4       daynum  
##    -8.57556     -1.94644      0.01134      0.03978
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(NTLbyALL.regression)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ depth + year4 + daynum + depth + 
##     noise, data = NTL.metagaming)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.6696 -3.0002  0.0921  2.9677 13.6017 
## 
## Coefficients:
##              Estimate Std. Error  t value Pr(>|t|)    
## (Intercept) -8.579389   8.631141   -0.994  0.32025    
## depth       -1.946437   0.011683 -166.603  < 2e-16 ***
## year4        0.011355   0.004299    2.641  0.00828 ** 
## daynum       0.039784   0.004317    9.215  < 2e-16 ***
## noise       -0.035213   0.135114   -0.261  0.79439    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.817 on 9723 degrees of freedom
## Multiple R-squared:  0.7412, Adjusted R-squared:  0.7411 
## F-statistic:  6961 on 4 and 9723 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Depth and day number seem the best suited (based on statistical significance) to predict temperature after running the AIC. }

\CommentTok{\#10}
\NormalTok{NTLBest.regression }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\AttributeTok{data=}\NormalTok{NTL.metagaming, temperature\_C }\SpecialCharTok{\textasciitilde{}}\NormalTok{ depth }\SpecialCharTok{+}\NormalTok{ year4 }\SpecialCharTok{+}\NormalTok{ daynum }\SpecialCharTok{+}\NormalTok{ depth)}
\FunctionTok{summary}\NormalTok{(NTLBest.regression)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ depth + year4 + daynum + depth, 
##     data = NTL.metagaming)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.6536 -3.0000  0.0902  2.9658 13.6123 
## 
## Coefficients:
##              Estimate Std. Error  t value Pr(>|t|)    
## (Intercept) -8.575564   8.630715   -0.994  0.32044    
## depth       -1.946437   0.011683 -166.611  < 2e-16 ***
## year4        0.011345   0.004299    2.639  0.00833 ** 
## daynum       0.039780   0.004317    9.215  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.817 on 9724 degrees of freedom
## Multiple R-squared:  0.7412, Adjusted R-squared:  0.7411 
## F-statistic:  9283 on 3 and 9724 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Ran the multiple regression lm function, which yielded similar results. At this point, NTL.metagaming and NTL\_Lake\_ChemPhys\_subset are the same data. }
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  What is the final set of explanatory variables that the AIC method
  suggests we use to predict temperature in our multiple regression? How
  much of the observed variance does this model explain? Is this an
  improvement over the model using only depth as the explanatory
  variable?
\end{enumerate}

\begin{quote}
Answer: The AIC uses year4, daynum and depth as explanatory variables,
though the year has the least statistical significance of the three. The
model explains 74.11\% of the observed variance, which is slightly
better than only using depth, but it does not seem like a large
increase.
\end{quote}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{analysis-of-variance}{%
\subsection{Analysis of Variance}\label{analysis-of-variance}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Now we want to see whether the different lakes have, on average,
  different temperatures in the month of July. Run an ANOVA test to
  complete this analysis. (No need to test assumptions of normality or
  similar variances.) Create two sets of models: one expressed as an
  ANOVA models and another expressed as a linear model (as done in our
  lessons).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#12}
\NormalTok{NTL.anova }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(}\AttributeTok{data =}\NormalTok{ NTL\_Lake\_ChemPhys\_subset, temperature\_C }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lakename)}
\FunctionTok{summary}\NormalTok{(NTL.anova)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Df Sum Sq Mean Sq F value Pr(>F)    
## lakename       8  21642  2705.2      50 <2e-16 ***
## Residuals   9719 525813    54.1                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{NTL.linearmodel }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(}\AttributeTok{data=}\NormalTok{NTL\_Lake\_ChemPhys\_subset, temperature\_C }\SpecialCharTok{\textasciitilde{}}\NormalTok{ lakename)}
\FunctionTok{summary}\NormalTok{(NTL.linearmodel)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ lakename, data = NTL_Lake_ChemPhys_subset)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -10.769  -6.614  -2.679   7.684  23.832 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)               17.6664     0.6501  27.174  < 2e-16 ***
## lakenameCrampton Lake     -2.3145     0.7699  -3.006 0.002653 ** 
## lakenameEast Long Lake    -7.3987     0.6918 -10.695  < 2e-16 ***
## lakenameHummingbird Lake  -6.8931     0.9429  -7.311 2.87e-13 ***
## lakenamePaul Lake         -3.8522     0.6656  -5.788 7.36e-09 ***
## lakenamePeter Lake        -4.3501     0.6645  -6.547 6.17e-11 ***
## lakenameTuesday Lake      -6.5972     0.6769  -9.746  < 2e-16 ***
## lakenameWard Lake         -3.2078     0.9429  -3.402 0.000672 ***
## lakenameWest Long Lake    -6.0878     0.6895  -8.829  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 7.355 on 9719 degrees of freedom
## Multiple R-squared:  0.03953,    Adjusted R-squared:  0.03874 
## F-statistic:    50 on 8 and 9719 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  Is there a significant difference in mean temperature among the lakes?
  Report your findings.
\end{enumerate}

\begin{quote}
Answer: There is a significant difference in mean temperatures among the
lakes, based on the p-values we get from running the linear model. All
of the lakes are showing high significance codes.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Create a graph that depicts temperature by depth, with a separate
  color for each lake. Add a geom\_smooth (method = ``lm'', se = FALSE)
  for each lake. Make your points 50 \% transparent. Adjust your y axis
  limits to go from 0 to 35 degrees. Clean up your graph to make it
  pretty.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#14.}
\NormalTok{NTL\_Lake\_ChemPhys\_plot2 }\OtherTok{\textless{}{-}}
\FunctionTok{ggplot}\NormalTok{(NTL\_Lake\_ChemPhys\_subset, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{depth,}\AttributeTok{y=}\NormalTok{temperature\_C,}\AttributeTok{color=}\NormalTok{lakename)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha=}\FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{35}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Depth"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Temperature (°C)"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Lake Temperature by Depth"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(NTL\_Lake\_ChemPhys\_plot2) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 73 rows containing missing values (`geom_smooth()`).
\end{verbatim}

\includegraphics{EmmaChilds_A06_GLMs_files/figure-latex/scatterplot.2-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\tightlist
\item
  Use the Tukey's HSD test to determine which lakes have different
  means.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#15}
\FunctionTok{TukeyHSD}\NormalTok{(NTL.anova)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = temperature_C ~ lakename, data = NTL_Lake_ChemPhys_subset)
## 
## $lakename
##                                          diff        lwr        upr     p adj
## Crampton Lake-Central Long Lake    -2.3145195 -4.7031913  0.0741524 0.0661566
## East Long Lake-Central Long Lake   -7.3987410 -9.5449411 -5.2525408 0.0000000
## Hummingbird Lake-Central Long Lake -6.8931304 -9.8184178 -3.9678430 0.0000000
## Paul Lake-Central Long Lake        -3.8521506 -5.9170942 -1.7872070 0.0000003
## Peter Lake-Central Long Lake       -4.3501458 -6.4115874 -2.2887042 0.0000000
## Tuesday Lake-Central Long Lake     -6.5971805 -8.6971605 -4.4972005 0.0000000
## Ward Lake-Central Long Lake        -3.2077856 -6.1330730 -0.2824982 0.0193405
## West Long Lake-Central Long Lake   -6.0877513 -8.2268550 -3.9486475 0.0000000
## East Long Lake-Crampton Lake       -5.0842215 -6.5591700 -3.6092730 0.0000000
## Hummingbird Lake-Crampton Lake     -4.5786109 -7.0538088 -2.1034131 0.0000004
## Paul Lake-Crampton Lake            -1.5376312 -2.8916215 -0.1836408 0.0127491
## Peter Lake-Crampton Lake           -2.0356263 -3.3842699 -0.6869828 0.0000999
## Tuesday Lake-Crampton Lake         -4.2826611 -5.6895065 -2.8758157 0.0000000
## Ward Lake-Crampton Lake            -0.8932661 -3.3684639  1.5819317 0.9714459
## West Long Lake-Crampton Lake       -3.7732318 -5.2378351 -2.3086285 0.0000000
## Hummingbird Lake-East Long Lake     0.5056106 -1.7364925  2.7477137 0.9988050
## Paul Lake-East Long Lake            3.5465903  2.6900206  4.4031601 0.0000000
## Peter Lake-East Long Lake           3.0485952  2.2005025  3.8966879 0.0000000
## Tuesday Lake-East Long Lake         0.8015604 -0.1363286  1.7394495 0.1657485
## Ward Lake-East Long Lake            4.1909554  1.9488523  6.4330585 0.0000002
## West Long Lake-East Long Lake       1.3109897  0.2885003  2.3334791 0.0022805
## Paul Lake-Hummingbird Lake          3.0409798  0.8765299  5.2054296 0.0004495
## Peter Lake-Hummingbird Lake         2.5429846  0.3818755  4.7040937 0.0080666
## Tuesday Lake-Hummingbird Lake       0.2959499 -1.9019508  2.4938505 0.9999752
## Ward Lake-Hummingbird Lake          3.6853448  0.6889874  6.6817022 0.0043297
## West Long Lake-Hummingbird Lake     0.8053791 -1.4299320  3.0406903 0.9717297
## Peter Lake-Paul Lake               -0.4979952 -1.1120620  0.1160717 0.2241586
## Tuesday Lake-Paul Lake             -2.7450299 -3.4781416 -2.0119182 0.0000000
## Ward Lake-Paul Lake                 0.6443651 -1.5200848  2.8088149 0.9916978
## West Long Lake-Paul Lake           -2.2356007 -3.0742314 -1.3969699 0.0000000
## Tuesday Lake-Peter Lake            -2.2470347 -2.9702236 -1.5238458 0.0000000
## Ward Lake-Peter Lake                1.1423602 -1.0187489  3.3034693 0.7827037
## West Long Lake-Peter Lake          -1.7376055 -2.5675759 -0.9076350 0.0000000
## Ward Lake-Tuesday Lake              3.3893950  1.1914943  5.5872956 0.0000609
## West Long Lake-Tuesday Lake         0.5094292 -0.4121051  1.4309636 0.7374387
## West Long Lake-Ward Lake           -2.8799657 -5.1152769 -0.6446546 0.0021080
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#16.}
\NormalTok{temp.lake.test }\OtherTok{\textless{}{-}} \FunctionTok{HSD.test}\NormalTok{(NTL.anova, }\StringTok{"lakename"}\NormalTok{, }\AttributeTok{group=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{temp.lake.test}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $statistics
##   MSerror   Df     Mean       CV
##   54.1016 9719 12.72087 57.82135
## 
## $parameters
##    test   name.t ntr StudentizedRange alpha
##   Tukey lakename   9         4.387504  0.05
## 
## $means
##                   temperature_C      std    r Min  Max    Q25   Q50    Q75
## Central Long Lake      17.66641 4.196292  128 8.9 26.8 14.400 18.40 21.000
## Crampton Lake          15.35189 7.244773  318 5.0 27.5  7.525 16.90 22.300
## East Long Lake         10.26767 6.766804  968 4.2 34.1  4.975  6.50 15.925
## Hummingbird Lake       10.77328 7.017845  116 4.0 31.5  5.200  7.00 15.625
## Paul Lake              13.81426 7.296928 2660 4.7 27.7  6.500 12.40 21.400
## Peter Lake             13.31626 7.669758 2872 4.0 27.0  5.600 11.40 21.500
## Tuesday Lake           11.06923 7.698687 1524 0.3 27.7  4.400  6.80 19.400
## Ward Lake              14.45862 7.409079  116 5.7 27.6  7.200 12.55 23.200
## West Long Lake         11.57865 6.980789 1026 4.0 25.7  5.400  8.00 18.800
## 
## $comparison
## NULL
## 
## $groups
##                   temperature_C groups
## Central Long Lake      17.66641      a
## Crampton Lake          15.35189     ab
## Ward Lake              14.45862     bc
## Paul Lake              13.81426      c
## Peter Lake             13.31626      c
## West Long Lake         11.57865      d
## Tuesday Lake           11.06923     de
## Hummingbird Lake       10.77328     de
## East Long Lake         10.26767      e
## 
## attr(,"class")
## [1] "group"
\end{verbatim}

16.From the findings above, which lakes have the same mean temperature,
statistically speaking, as Peter Lake? Does any lake have a mean
temperature that is statistically distinct from all the other lakes?

\begin{quote}
Answer: Statistically speaking, Ward Lake, Paul Lake and Peter Lake all
are in the same ``c'' group provided by the HSD test, which indicates
they have similar mean temperatures. It does not look like any lake is
in a category all by itself, so based on that, no, none appear to be
statistically distinct from all the other lakes.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{16}
\tightlist
\item
  If we were just looking at Peter Lake and Paul Lake. What's another
  test we might explore to see whether they have distinct mean
  temperatures?
\end{enumerate}

\begin{quote}
Answer: We could run a two-sample t-test to assess their mean
temperatures and statistical significance.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{17}
\tightlist
\item
  Wrangle the July data to include only records for Crampton Lake and
  Ward Lake. Run the two-sample T-test on these data to determine
  whether their July temperature are same or different. What does the
  test say? Are the mean temperatures for the lakes equal? Does that
  match you answer for part 16?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{NTL.ward.crampton }\OtherTok{\textless{}{-}}\NormalTok{ NTL\_Lake\_ChemPhys\_subset }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(lakename }\SpecialCharTok{==} \StringTok{"Crampton Lake"} \SpecialCharTok{|}\NormalTok{ lakename }\SpecialCharTok{==} \StringTok{"Ward Lake"}\NormalTok{)}
\NormalTok{NTL.ward.crampton}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          lakename year4 daynum depth temperature_C
## 1   Crampton Lake  1999    196  0.00          22.8
## 2   Crampton Lake  1999    196  0.50          22.6
## 3   Crampton Lake  1999    196  1.00          22.4
## 4   Crampton Lake  1999    196  1.50          22.2
## 5   Crampton Lake  1999    196  2.00          22.0
## 6   Crampton Lake  1999    196  2.50          21.9
## 7   Crampton Lake  1999    196  3.00          21.7
## 8   Crampton Lake  1999    196  3.50          21.3
## 9   Crampton Lake  1999    196  4.00          20.0
## 10  Crampton Lake  1999    196  4.50          17.1
## 11  Crampton Lake  1999    196  5.00          14.4
## 12  Crampton Lake  1999    196  5.50          12.1
## 13  Crampton Lake  1999    196  6.00          10.2
## 14  Crampton Lake  1999    196  6.50           9.1
## 15  Crampton Lake  1999    196  7.00           8.4
## 16  Crampton Lake  1999    196  8.00           7.1
## 17  Crampton Lake  1999    196  9.00           6.3
## 18  Crampton Lake  1999    196 10.00           5.8
## 19  Crampton Lake  1999    196 11.00           5.5
## 20  Crampton Lake  1999    196 12.00           5.4
## 21  Crampton Lake  2003    183  0.00          21.8
## 22  Crampton Lake  2003    183  0.50          21.9
## 23  Crampton Lake  2003    183  1.00          21.9
## 24  Crampton Lake  2003    183  1.50          21.8
## 25  Crampton Lake  2003    183  2.00          21.8
## 26  Crampton Lake  2003    183  2.50          21.3
## 27  Crampton Lake  2003    183  3.00          20.8
## 28  Crampton Lake  2003    183  3.50          19.9
## 29  Crampton Lake  2003    183  4.00          17.2
## 30  Crampton Lake  2003    183  4.50          15.2
## 31  Crampton Lake  2003    183  5.00          12.7
## 32  Crampton Lake  2003    183  5.50          11.2
## 33  Crampton Lake  2003    183  6.00          10.2
## 34  Crampton Lake  2003    183  6.50           8.8
## 35  Crampton Lake  2003    183  7.00           8.2
## 36  Crampton Lake  2003    183  8.00           6.8
## 37  Crampton Lake  2003    183  9.00           6.0
## 38  Crampton Lake  2003    183 10.00           5.4
## 39  Crampton Lake  2003    183 11.00           5.1
## 40  Crampton Lake  2003    183 12.00           5.0
## 41  Crampton Lake  2003    197  0.00          22.2
## 42  Crampton Lake  2003    197  0.50          21.9
## 43  Crampton Lake  2003    197  1.00          21.8
## 44  Crampton Lake  2003    197  1.50          21.8
## 45  Crampton Lake  2003    197  2.00          21.7
## 46  Crampton Lake  2003    197  2.50          21.7
## 47  Crampton Lake  2003    197  3.00          21.7
## 48  Crampton Lake  2003    197  3.50          21.6
## 49  Crampton Lake  2003    197  4.00          19.6
## 50  Crampton Lake  2003    197  4.50          17.3
## 51  Crampton Lake  2003    197  5.00          14.5
## 52  Crampton Lake  2003    197  5.50          12.5
## 53  Crampton Lake  2003    197  6.00          10.9
## 54  Crampton Lake  2003    197  6.50           9.8
## 55  Crampton Lake  2003    197  7.00           8.7
## 56  Crampton Lake  2003    197  8.00           7.0
## 57  Crampton Lake  2003    197  9.00           6.0
## 58  Crampton Lake  2003    197 10.00           5.5
## 59  Crampton Lake  2003    197 11.00           5.2
## 60  Crampton Lake  2003    197 12.00           5.1
## 61  Crampton Lake  2003    211  0.00          23.2
## 62  Crampton Lake  2003    211  0.50          23.3
## 63  Crampton Lake  2003    211  1.00          23.2
## 64  Crampton Lake  2003    211  1.50          23.3
## 65  Crampton Lake  2003    211  2.00          23.3
## 66  Crampton Lake  2003    211  2.50          23.3
## 67  Crampton Lake  2003    211  3.00          23.3
## 68  Crampton Lake  2003    211  3.50          23.2
## 69  Crampton Lake  2003    211  4.00          22.4
## 70  Crampton Lake  2003    211  4.50          20.6
## 71  Crampton Lake  2003    211  5.00          17.3
## 72  Crampton Lake  2003    211  5.50          14.6
## 73  Crampton Lake  2003    211  6.00          12.1
## 74  Crampton Lake  2003    211  6.50          11.0
## 75  Crampton Lake  2003    211  7.00           9.6
## 76  Crampton Lake  2003    211  8.00           7.4
## 77  Crampton Lake  2003    211  9.00           6.4
## 78  Crampton Lake  2003    211 10.00           5.7
## 79  Crampton Lake  2003    211 11.00           5.4
## 80  Crampton Lake  2003    211 12.00           5.2
## 81  Crampton Lake  2004    183  0.00          19.8
## 82  Crampton Lake  2004    183  0.50          19.8
## 83  Crampton Lake  2004    183  1.00          19.8
## 84  Crampton Lake  2004    183  1.50          19.8
## 85  Crampton Lake  2004    183  2.00          19.7
## 86  Crampton Lake  2004    183  2.50          19.5
## 87  Crampton Lake  2004    183  3.00          18.9
## 88  Crampton Lake  2004    183  3.50          18.4
## 89  Crampton Lake  2004    183  4.00          18.0
## 90  Crampton Lake  2004    183  4.50          17.5
## 91  Crampton Lake  2004    183  5.00          15.6
## 92  Crampton Lake  2004    183  5.50          13.4
## 93  Crampton Lake  2004    183  6.00          11.2
## 94  Crampton Lake  2004    183  6.50          10.2
## 95  Crampton Lake  2004    183  7.00           9.0
## 96  Crampton Lake  2004    183  8.00           7.6
## 97  Crampton Lake  2004    183  9.00           6.6
## 98  Crampton Lake  2004    183 10.00           6.0
## 99  Crampton Lake  2004    183 11.00           5.6
## 100 Crampton Lake  2004    183 12.00           5.5
## 101 Crampton Lake  2004    183 13.00           5.5
## 102 Crampton Lake  2004    183 14.00           5.5
## 103 Crampton Lake  2004    191  0.00          18.1
## 104 Crampton Lake  2004    191  0.50          18.1
## 105 Crampton Lake  2004    191  1.00          18.0
## 106 Crampton Lake  2004    191  1.50          18.0
## 107 Crampton Lake  2004    191  2.00          17.9
## 108 Crampton Lake  2004    191  2.50          17.9
## 109 Crampton Lake  2004    191  3.00          17.9
## 110 Crampton Lake  2004    191  3.50          17.8
## 111 Crampton Lake  2004    191  4.00          17.6
## 112 Crampton Lake  2004    191  4.50          17.4
## 113 Crampton Lake  2004    191  5.00          16.6
## 114 Crampton Lake  2004    191  5.50          13.8
## 115 Crampton Lake  2004    191  6.00          12.1
## 116 Crampton Lake  2004    191  6.50          10.9
## 117 Crampton Lake  2004    191  7.00           9.4
## 118 Crampton Lake  2004    191  8.00           7.6
## 119 Crampton Lake  2004    191  9.00           6.6
## 120 Crampton Lake  2004    191 10.00           6.0
## 121 Crampton Lake  2004    191 11.00           5.7
## 122 Crampton Lake  2004    191 12.00           5.6
## 123 Crampton Lake  2004    191 13.00           5.5
## 124 Crampton Lake  2004    191 14.00           5.5
## 125 Crampton Lake  2004    197  0.00          21.8
## 126 Crampton Lake  2004    197  0.50          21.8
## 127 Crampton Lake  2004    197  1.00          21.6
## 128 Crampton Lake  2004    197  1.50          21.6
## 129 Crampton Lake  2004    197  2.00          21.5
## 130 Crampton Lake  2004    197  2.50          20.9
## 131 Crampton Lake  2004    197  3.00          19.5
## 132 Crampton Lake  2004    197  3.50          19.1
## 133 Crampton Lake  2004    197  4.00          18.6
## 134 Crampton Lake  2004    197  4.50          17.9
## 135 Crampton Lake  2004    197  5.00          16.7
## 136 Crampton Lake  2004    197  5.50          14.8
## 137 Crampton Lake  2004    197  6.00          12.8
## 138 Crampton Lake  2004    197  6.50          11.1
## 139 Crampton Lake  2004    197  7.00           9.7
## 140 Crampton Lake  2004    197  8.00           7.7
## 141 Crampton Lake  2004    197  9.00           6.6
## 142 Crampton Lake  2004    197 10.00           6.1
## 143 Crampton Lake  2004    197 11.00           5.7
## 144 Crampton Lake  2004    197 12.00           5.6
## 145 Crampton Lake  2004    197 13.00           5.6
## 146 Crampton Lake  2004    197 14.00           5.5
## 147 Crampton Lake  2004    204  0.00          23.8
## 148 Crampton Lake  2004    204  0.50          23.8
## 149 Crampton Lake  2004    204  1.00          23.8
## 150 Crampton Lake  2004    204  1.50          23.8
## 151 Crampton Lake  2004    204  2.00          23.8
## 152 Crampton Lake  2004    204  2.50          23.2
## 153 Crampton Lake  2004    204  3.00          22.0
## 154 Crampton Lake  2004    204  3.50          20.5
## 155 Crampton Lake  2004    204  4.00          19.9
## 156 Crampton Lake  2004    204  4.50          18.5
## 157 Crampton Lake  2004    204  5.00          17.3
## 158 Crampton Lake  2004    204  5.50          15.5
## 159 Crampton Lake  2004    204  6.00          13.5
## 160 Crampton Lake  2004    204  6.50          11.3
## 161 Crampton Lake  2004    204  7.00          10.1
## 162 Crampton Lake  2004    204  8.00           7.8
## 163 Crampton Lake  2004    204  9.00           6.8
## 164 Crampton Lake  2004    204 10.00           6.2
## 165 Crampton Lake  2004    204 11.00           5.8
## 166 Crampton Lake  2004    204 12.00           5.7
## 167 Crampton Lake  2004    204 13.00           5.6
## 168 Crampton Lake  2004    204 14.00           5.6
## 169 Crampton Lake  2004    211  0.00          22.7
## 170 Crampton Lake  2004    211  0.50          22.7
## 171 Crampton Lake  2004    211  1.00          22.7
## 172 Crampton Lake  2004    211  1.50          22.7
## 173 Crampton Lake  2004    211  2.00          22.7
## 174 Crampton Lake  2004    211  2.50          22.7
## 175 Crampton Lake  2004    211  3.00          22.7
## 176 Crampton Lake  2004    211  3.50          22.6
## 177 Crampton Lake  2004    211  4.00          20.8
## 178 Crampton Lake  2004    211  4.50          18.1
## 179 Crampton Lake  2004    211  5.00          17.5
## 180 Crampton Lake  2004    211  5.50          15.8
## 181 Crampton Lake  2004    211  6.00          13.6
## 182 Crampton Lake  2004    211  6.50          11.5
## 183 Crampton Lake  2004    211  7.00          10.3
## 184 Crampton Lake  2004    211  8.00           7.8
## 185 Crampton Lake  2004    211  9.00           6.8
## 186 Crampton Lake  2004    211 10.00           6.2
## 187 Crampton Lake  2004    211 11.00           5.8
## 188 Crampton Lake  2004    211 12.00           5.7
## 189 Crampton Lake  2004    211 13.00           5.6
## 190 Crampton Lake  2004    211 14.00           5.6
## 191 Crampton Lake  2005    186  0.00          22.3
## 192 Crampton Lake  2005    186  0.50          22.3
## 193 Crampton Lake  2005    186  1.00          22.4
## 194 Crampton Lake  2005    186  1.50          22.4
## 195 Crampton Lake  2005    186  2.00          22.4
## 196 Crampton Lake  2005    186  2.50          22.4
## 197 Crampton Lake  2005    186  3.00          22.4
## 198 Crampton Lake  2005    186  3.50          22.3
## 199 Crampton Lake  2005    186  4.00          22.3
## 200 Crampton Lake  2005    186  4.50          21.5
## 201 Crampton Lake  2005    186  5.00          17.9
## 202 Crampton Lake  2005    186  5.50          15.3
## 203 Crampton Lake  2005    186  6.00          13.5
## 204 Crampton Lake  2005    186  6.50          12.3
## 205 Crampton Lake  2005    186  7.00          10.8
## 206 Crampton Lake  2005    186  8.00           8.8
## 207 Crampton Lake  2005    186  9.00           7.4
## 208 Crampton Lake  2005    186 10.00           6.0
## 209 Crampton Lake  2005    186 11.00           5.8
## 210 Crampton Lake  2005    186 12.00           5.7
## 211 Crampton Lake  2005    192  0.00          25.7
## 212 Crampton Lake  2005    192  0.50          25.7
## 213 Crampton Lake  2005    192  1.00          25.4
## 214 Crampton Lake  2005    192  1.50          25.4
## 215 Crampton Lake  2005    192  2.00          25.3
## 216 Crampton Lake  2005    192  2.50          24.2
## 217 Crampton Lake  2005    192  3.00          23.5
## 218 Crampton Lake  2005    192  3.50          22.9
## 219 Crampton Lake  2005    192  4.00          22.5
## 220 Crampton Lake  2005    192  4.50          21.4
## 221 Crampton Lake  2005    192  5.00          19.5
## 222 Crampton Lake  2005    192  5.50          16.5
## 223 Crampton Lake  2005    192  6.00          14.6
## 224 Crampton Lake  2005    192  6.50          12.9
## 225 Crampton Lake  2005    192  7.00          11.4
## 226 Crampton Lake  2005    192  8.00           9.0
## 227 Crampton Lake  2005    192  9.00           7.5
## 228 Crampton Lake  2005    192 10.00           6.5
## 229 Crampton Lake  2005    192 11.00           6.0
## 230 Crampton Lake  2005    192 12.00           5.7
## 231 Crampton Lake  2005    192 13.00           5.6
## 232 Crampton Lake  2005    199  0.00          27.5
## 233 Crampton Lake  2005    199  0.50          27.5
## 234 Crampton Lake  2005    199  1.00          27.5
## 235 Crampton Lake  2005    199  1.50          27.4
## 236 Crampton Lake  2005    199  2.00          27.4
## 237 Crampton Lake  2005    199  2.50          27.4
## 238 Crampton Lake  2005    199  3.00          26.0
## 239 Crampton Lake  2005    199  3.50          24.8
## 240 Crampton Lake  2005    199  4.00          23.7
## 241 Crampton Lake  2005    199  4.50          22.5
## 242 Crampton Lake  2005    199  5.00          19.8
## 243 Crampton Lake  2005    199  5.50          17.1
## 244 Crampton Lake  2005    199  6.00          15.3
## 245 Crampton Lake  2005    199  6.50          13.5
## 246 Crampton Lake  2005    199  7.00          12.0
## 247 Crampton Lake  2005    199  8.00           9.0
## 248 Crampton Lake  2005    199  9.00           7.7
## 249 Crampton Lake  2005    199 10.00           6.6
## 250 Crampton Lake  2005    199 11.00           6.1
## 251 Crampton Lake  2005    199 12.00           5.7
## 252 Crampton Lake  2005    199 13.00           5.7
## 253 Crampton Lake  2005    206  0.00          25.3
## 254 Crampton Lake  2005    206  0.50          25.1
## 255 Crampton Lake  2005    206  1.00          25.0
## 256 Crampton Lake  2005    206  1.50          24.9
## 257 Crampton Lake  2005    206  2.00          24.9
## 258 Crampton Lake  2005    206  2.50          24.9
## 259 Crampton Lake  2005    206  3.00          24.8
## 260 Crampton Lake  2005    206  3.50          24.8
## 261 Crampton Lake  2005    206  4.00          24.7
## 262 Crampton Lake  2005    206  4.50          24.5
## 263 Crampton Lake  2005    206  5.00          21.3
## 264 Crampton Lake  2005    206  5.50          18.8
## 265 Crampton Lake  2005    206  6.00          16.7
## 266 Crampton Lake  2005    206  6.50          14.4
## 267 Crampton Lake  2005    206  7.00          12.3
## 268 Crampton Lake  2005    206  8.00           9.9
## 269 Crampton Lake  2005    206  9.00           7.9
## 270 Crampton Lake  2005    206 10.00           6.8
## 271 Crampton Lake  2005    206 11.00           6.1
## 272 Crampton Lake  2005    206 12.00           5.8
## 273 Crampton Lake  2005    206 13.00           5.7
## 274 Crampton Lake  2006    186  0.00          22.7
## 275 Crampton Lake  2006    186  0.50          22.8
## 276 Crampton Lake  2006    186  1.00          22.8
## 277 Crampton Lake  2006    186  1.50          22.8
## 278 Crampton Lake  2006    186  2.00          22.8
## 279 Crampton Lake  2006    186  2.50          22.5
## 280 Crampton Lake  2006    186  3.00          22.6
## 281 Crampton Lake  2006    186  3.50          22.6
## 282 Crampton Lake  2006    186  4.00          20.3
## 283 Crampton Lake  2006    186  4.50          17.4
## 284 Crampton Lake  2006    186  5.00          15.2
## 285 Crampton Lake  2006    186  5.50          13.7
## 286 Crampton Lake  2006    186  6.00          12.1
## 287 Crampton Lake  2006    186  6.50          10.8
## 288 Crampton Lake  2006    186  7.00           9.6
## 289 Crampton Lake  2006    186  7.50           8.3
## 290 Crampton Lake  2006    186  8.00           7.4
## 291 Crampton Lake  2006    186  8.50           6.3
## 292 Crampton Lake  2006    186  9.00           6.0
## 293 Crampton Lake  2006    186 10.00           5.5
## 294 Crampton Lake  2006    186 11.00           5.2
## 295 Crampton Lake  2006    186 12.00           5.1
## 296 Crampton Lake  2006    200  0.00          25.4
## 297 Crampton Lake  2006    200  0.50          25.4
## 298 Crampton Lake  2006    200  1.00          25.4
## 299 Crampton Lake  2006    200  1.50          25.4
## 300 Crampton Lake  2006    200  2.00          25.4
## 301 Crampton Lake  2006    200  2.50          25.4
## 302 Crampton Lake  2006    200  3.00          25.4
## 303 Crampton Lake  2006    200  3.50          24.1
## 304 Crampton Lake  2006    200  4.00          22.5
## 305 Crampton Lake  2006    200  4.50          19.8
## 306 Crampton Lake  2006    200  5.00          17.5
## 307 Crampton Lake  2006    200  5.50          15.0
## 308 Crampton Lake  2006    200  6.00          13.3
## 309 Crampton Lake  2006    200  6.50          11.4
## 310 Crampton Lake  2006    200  7.00           9.6
## 311 Crampton Lake  2006    200  7.50           8.7
## 312 Crampton Lake  2006    200  8.00           7.5
## 313 Crampton Lake  2006    200  8.50           6.7
## 314 Crampton Lake  2006    200  9.00           6.4
## 315 Crampton Lake  2006    200 10.00           5.7
## 316 Crampton Lake  2006    200 11.00           5.4
## 317 Crampton Lake  2006    200 12.00           5.1
## 318 Crampton Lake  2006    200 13.00           5.1
## 319     Ward Lake  2010    188  0.00          25.5
## 320     Ward Lake  2010    188  0.50          25.3
## 321     Ward Lake  2010    188  0.75          24.9
## 322     Ward Lake  2010    188  1.00          24.8
## 323     Ward Lake  2010    188  1.50          23.7
## 324     Ward Lake  2010    188  2.00          21.8
## 325     Ward Lake  2010    188  2.50          18.6
## 326     Ward Lake  2010    188  3.00          16.6
## 327     Ward Lake  2010    188  3.50          14.6
## 328     Ward Lake  2010    188  4.00          12.5
## 329     Ward Lake  2010    188  4.50          10.4
## 330     Ward Lake  2010    188  5.00           9.0
## 331     Ward Lake  2010    188  5.50           7.7
## 332     Ward Lake  2010    188  6.00           7.1
## 333     Ward Lake  2010    188  6.50           6.9
## 334     Ward Lake  2010    188  6.75           6.7
## 335     Ward Lake  2010    195  0.00          24.1
## 336     Ward Lake  2010    195  0.50          24.1
## 337     Ward Lake  2010    195  1.00          24.0
## 338     Ward Lake  2010    195  1.50          23.9
## 339     Ward Lake  2010    195  2.00          23.2
## 340     Ward Lake  2010    195  2.50          20.3
## 341     Ward Lake  2010    195  3.00          17.4
## 342     Ward Lake  2010    195  3.50          14.7
## 343     Ward Lake  2010    195  4.00          12.5
## 344     Ward Lake  2010    195  4.50          10.6
## 345     Ward Lake  2010    195  5.00           8.8
## 346     Ward Lake  2010    195  5.50           7.7
## 347     Ward Lake  2010    195  6.00           7.2
## 348     Ward Lake  2010    195  6.50           7.0
## 349     Ward Lake  2010    202  0.00          23.9
## 350     Ward Lake  2010    202  0.50          23.8
## 351     Ward Lake  2010    202  1.00          23.7
## 352     Ward Lake  2010    202  1.50          23.3
## 353     Ward Lake  2010    202  2.00          23.1
## 354     Ward Lake  2010    202  2.50          20.7
## 355     Ward Lake  2010    202  3.00          17.0
## 356     Ward Lake  2010    202  3.50          15.1
## 357     Ward Lake  2010    202  4.00          12.6
## 358     Ward Lake  2010    202  4.50          10.7
## 359     Ward Lake  2010    202  5.00           9.1
## 360     Ward Lake  2010    202  5.50           7.9
## 361     Ward Lake  2010    202  6.00           7.3
## 362     Ward Lake  2010    202  6.50           7.1
## 363     Ward Lake  2010    202  7.00           7.1
## 364     Ward Lake  2010    209  0.00          23.6
## 365     Ward Lake  2010    209  0.50          23.6
## 366     Ward Lake  2010    209  1.00          23.5
## 367     Ward Lake  2010    209  1.50          23.4
## 368     Ward Lake  2010    209  2.00          23.1
## 369     Ward Lake  2010    209  2.50          21.0
## 370     Ward Lake  2010    209  3.00          18.2
## 371     Ward Lake  2010    209  3.50          15.7
## 372     Ward Lake  2010    209  4.00          13.4
## 373     Ward Lake  2010    209  4.50          11.1
## 374     Ward Lake  2010    209  5.00           9.2
## 375     Ward Lake  2010    209  5.50           8.0
## 376     Ward Lake  2010    209  6.00           7.4
## 377     Ward Lake  2010    209  6.50           7.2
## 378     Ward Lake  2010    209  6.75           7.0
## 379     Ward Lake  2012    187  0.00          27.6
## 380     Ward Lake  2012    187  0.50          27.0
## 381     Ward Lake  2012    187  1.00          24.6
## 382     Ward Lake  2012    187  1.50          20.4
## 383     Ward Lake  2012    187  2.00          15.8
## 384     Ward Lake  2012    187  2.50          12.3
## 385     Ward Lake  2012    187  3.00          10.2
## 386     Ward Lake  2012    187  3.50           7.9
## 387     Ward Lake  2012    187  4.00           6.9
## 388     Ward Lake  2012    187  4.50           6.4
## 389     Ward Lake  2012    187  5.00           6.1
## 390     Ward Lake  2012    187  5.50           5.8
## 391     Ward Lake  2012    187  6.00           5.7
## 392     Ward Lake  2012    194  0.00          25.9
## 393     Ward Lake  2012    194  0.50          25.1
## 394     Ward Lake  2012    194  1.00          24.5
## 395     Ward Lake  2012    194  1.50          20.8
## 396     Ward Lake  2012    194  2.00          16.5
## 397     Ward Lake  2012    194  2.50          12.6
## 398     Ward Lake  2012    194  3.00          10.3
## 399     Ward Lake  2012    194  3.50           8.2
## 400     Ward Lake  2012    194  4.00           7.2
## 401     Ward Lake  2012    194  4.50           6.6
## 402     Ward Lake  2012    194  5.00           6.3
## 403     Ward Lake  2012    194  5.50           6.0
## 404     Ward Lake  2012    194  6.00           5.9
## 405     Ward Lake  2012    201  0.00          23.6
## 406     Ward Lake  2012    201  0.50          23.3
## 407     Ward Lake  2012    201  1.00          23.2
## 408     Ward Lake  2012    201  1.50          21.5
## 409     Ward Lake  2012    201  2.00          16.9
## 410     Ward Lake  2012    201  2.50          13.2
## 411     Ward Lake  2012    201  3.00          10.3
## 412     Ward Lake  2012    201  3.50           8.6
## 413     Ward Lake  2012    201  4.00           7.7
## 414     Ward Lake  2012    201  4.50           6.8
## 415     Ward Lake  2012    201  5.00           6.4
## 416     Ward Lake  2012    201  5.50           6.2
## 417     Ward Lake  2012    201  6.00           6.0
## 418     Ward Lake  2012    201  6.50           5.9
## 419     Ward Lake  2012    201  7.00           5.8
## 420     Ward Lake  2012    208  0.00          24.3
## 421     Ward Lake  2012    208  0.50          24.2
## 422     Ward Lake  2012    208  1.00          24.2
## 423     Ward Lake  2012    208  1.50          22.3
## 424     Ward Lake  2012    208  2.00          17.5
## 425     Ward Lake  2012    208  2.50          13.7
## 426     Ward Lake  2012    208  3.00          10.5
## 427     Ward Lake  2012    208  3.50           8.5
## 428     Ward Lake  2012    208  4.00           7.6
## 429     Ward Lake  2012    208  4.50           6.8
## 430     Ward Lake  2012    208  5.00           6.4
## 431     Ward Lake  2012    208  5.50           6.1
## 432     Ward Lake  2012    208  6.00           6.0
## 433     Ward Lake  2012    208  6.50           5.9
## 434     Ward Lake  2012    208  7.00           5.8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{NTL.twosample }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(NTL.ward.crampton}\SpecialCharTok{$}\NormalTok{temperature\_C }\SpecialCharTok{\textasciitilde{}}\NormalTok{ NTL.ward.crampton}\SpecialCharTok{$}\NormalTok{lakename) }
\NormalTok{NTL.twosample}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  NTL.ward.crampton$temperature_C by NTL.ward.crampton$lakename
## t = 1.1181, df = 200.37, p-value = 0.2649
## alternative hypothesis: true difference in means between group Crampton Lake and group Ward Lake is not equal to 0
## 95 percent confidence interval:
##  -0.6821129  2.4686451
## sample estimates:
## mean in group Crampton Lake     mean in group Ward Lake 
##                    15.35189                    14.45862
\end{verbatim}

\begin{quote}
Answer: The means for Crampton Lake and Ward Lake seem generally
similar, just looking at numbers (15.35 vs 14.46). The test indicates
the p-value is 0.2649, which is not statistically significant in terms
of their means being different. So yes, this matches our answer from
part 16.
\end{quote}

\end{document}
